# Generated by Django 4.2.2 on 2024-02-22 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0014_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data_envio']},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='conversa',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Conversa',
        ),
    ]
