# Generated by Django 4.2.2 on 2024-02-22 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0016_alter_mensagem_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
